"""
Sample Mercari Japan product data for simulation
In production, this would be replaced with actual scraping from Mercari Japan
"""

SAMPLE_MERCARI_DATA = [
    {
        "id": "m001",
        "name": "iPhone 14 Pro Max 256GB スペースブラック",
        "price": 128000,
        "condition": "very_good",
        "seller_rating": 4.8,
        "category": "Electronics",
        "brand": "Apple",
        "image_url": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m001",
        "description": "iPhone 14 Pro Max in excellent condition. Minor wear on corners."
    },
    {
        "id": "m002",
        "name": "Nintendo Switch 有機ELモデル ホワイト",
        "price": 35800,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Gaming",
        "brand": "Nintendo",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m002",
        "description": "Nintendo Switch OLED model in pristine condition with original box."
    },
    {
        "id": "m003",
        "name": "MacBook Air M2 13インチ スターライト 8GB/256GB",
        "price": 145000,
        "condition": "good",
        "seller_rating": 4.7,
        "category": "Electronics",
        "brand": "Apple",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m003",
        "description": "MacBook Air M2 in good working condition. Some scratches on lid."
    },
    {
        "id": "m004",
        "name": "ポケモンカード ピカチュウ プロモ PSA10",
        "price": 25000,
        "condition": "new",
        "seller_rating": 4.6,
        "category": "Trading Cards",
        "brand": "Pokemon",
        "image_url": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m004",
        "description": "PSA 10 graded Pikachu promotional card in perfect condition."
    },
    {
        "id": "m005",
        "name": "AirPods Pro 第2世代 MQD83J/A",
        "price": 28000,
        "condition": "very_good",
        "seller_rating": 4.8,
        "category": "Electronics",
        "brand": "Apple",
        "image_url": "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m005",
        "description": "AirPods Pro 2nd generation with original charging case and accessories."
    },
    {
        "id": "m006",
        "name": "ルイヴィトン モノグラム スピーディ30",
        "price": 85000,
        "condition": "good",
        "seller_rating": 4.5,
        "category": "Fashion",
        "brand": "Louis Vuitton",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m006",
        "description": "Authentic Louis Vuitton Monogram Speedy 30 handbag."
    },
    {
        "id": "m007",
        "name": "PlayStation 5 本体 CFI-1200A01",
        "price": 68000,
        "condition": "very_good",
        "seller_rating": 4.9,
        "category": "Gaming",
        "brand": "Sony",
        "image_url": "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m007",
        "description": "PlayStation 5 console in excellent condition with all original accessories."
    },
    {
        "id": "m008",
        "name": "ロレックス サブマリーナ 116610LN",
        "price": 1250000,
        "condition": "very_good",
        "seller_rating": 4.7,
        "category": "Watches",
        "brand": "Rolex",
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m008",
        "description": "Rolex Submariner Date with box and papers. Serviced recently."
    },
    {
        "id": "m009",
        "name": "iPad Pro 12.9インチ 第6世代 Wi-Fi 128GB スペースグレイ",
        "price": 125000,
        "condition": "like_new",
        "seller_rating": 4.8,
        "category": "Electronics",
        "brand": "Apple",
        "image_url": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m009",
        "description": "iPad Pro 12.9-inch 6th generation in like-new condition with screen protector."
    },
    {
        "id": "m010",
        "name": "デュエルマスターズ ブラック・ロータス プロモ",
        "price": 45000,
        "condition": "good",
        "seller_rating": 4.6,
        "category": "Trading Cards",
        "brand": "Takara Tomy",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m010",
        "description": "Duel Masters Black Lotus promotional card in good condition."
    },
    {
        "id": "m011",
        "name": "チャンピオン リバースウィーブ パーカー USA製 ビンテージ",
        "price": 15000,
        "condition": "good",
        "seller_rating": 4.4,
        "category": "Fashion",
        "brand": "Champion",
        "image_url": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m011",
        "description": "Vintage Champion Reverse Weave hoodie made in USA."
    },
    {
        "id": "m012",
        "name": "Canon EOS R6 Mark II ボディ",
        "price": 285000,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Electronics",
        "brand": "Canon",
        "image_url": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m012",
        "description": "Canon EOS R6 Mark II camera body in excellent condition with low shutter count."
    },
    {
        "id": "m013",
        "name": "フェンディ バゲット バッグ ズッカ柄",
        "price": 120000,
        "condition": "good",
        "seller_rating": 4.6,
        "category": "Fashion",
        "brand": "Fendi",
        "image_url": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m013",
        "description": "Authentic Fendi Baguette bag in Zucca canvas pattern."
    },
    {
        "id": "m014",
        "name": "ワンピース フィギュア ルフィ ギア5 POP",
        "price": 18000,
        "condition": "new",
        "seller_rating": 4.7,
        "category": "Collectibles",
        "brand": "Megahouse",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m014",
        "description": "One Piece Luffy Gear 5 figure by Megahouse, brand new in box."
    },
    {
        "id": "m015",
        "name": "Supreme Box Logo パーカー グレー Lサイズ",
        "price": 55000,
        "condition": "very_good",
        "seller_rating": 4.5,
        "category": "Fashion",
        "brand": "Supreme",
        "image_url": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m015",
        "description": "Supreme Box Logo hoodie in grey, size L, authentic with tags."
    },
    {
        "id": "m016",
        "name": "CHANEL ココマーク イヤリング ゴールド",
        "price": 65000,
        "condition": "very_good",
        "seller_rating": 4.8,
        "category": "Fashion",
        "brand": "Chanel",
        "image_url": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m016",
        "description": "Authentic Chanel Coco mark earrings in gold, excellent condition."
    },
    {
        "id": "m017",
        "name": "遊戯王 ブルーアイズホワイトドラゴン 初期",
        "price": 35000,
        "condition": "good",
        "seller_rating": 4.7,
        "category": "Trading Cards",
        "brand": "Konami",
        "image_url": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m017",
        "description": "Yu-Gi-Oh Blue-Eyes White Dragon first edition card in good condition."
    },
    {
        "id": "m018",
        "name": "ドラゴンボール フィギュア 超サイヤ人悟空",
        "price": 12000,
        "condition": "new",
        "seller_rating": 4.9,
        "category": "Collectibles",
        "brand": "Bandai",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m018",
        "description": "Dragon Ball Super Saiyan Goku figure by Bandai, brand new in box."
    },
    {
        "id": "m019",
        "name": "iPhone 15 Pro 128GB ナチュラルチタニウム",
        "price": 165000,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Electronics",
        "brand": "Apple",
        "image_url": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m019",
        "description": "iPhone 15 Pro 128GB in Natural Titanium, like new condition with box."
    },
    {
        "id": "m020",
        "name": "Nike Air Jordan 1 Retro High OG シカゴ",
        "price": 48000,
        "condition": "very_good",
        "seller_rating": 4.6,
        "category": "Fashion",
        "brand": "Nike",
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m020",
        "description": "Nike Air Jordan 1 Retro High OG Chicago colorway in very good condition."
    },
    {
        "id": "m021",
        "name": "Sony WH-1000XM5 ワイヤレスヘッドホン",
        "price": 32000,
        "condition": "like_new",
        "seller_rating": 4.8,
        "category": "Electronics",
        "brand": "Sony",
        "image_url": "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m021",
        "description": "Sony WH-1000XM5 wireless noise-canceling headphones, like new."
    },
    {
        "id": "m022",
        "name": "任天堂 ゲームボーイ ポケットモンスター 赤",
        "price": 8500,
        "condition": "good",
        "seller_rating": 4.5,
        "category": "Gaming",
        "brand": "Nintendo",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m022",
        "description": "Nintendo Game Boy Pokémon Red version in good working condition."
    },
    {
        "id": "m023",
        "name": "グッチ GGマーモント レザーベルト",
        "price": 42000,
        "condition": "very_good",
        "seller_rating": 4.7,
        "category": "Fashion",
        "brand": "Gucci",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m023",
        "description": "Authentic Gucci GG Marmont leather belt in very good condition."
    },
    {
        "id": "m024",
        "name": "ダイソン V15 Detect コードレス掃除機",
        "price": 68000,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Home & Kitchen",
        "brand": "Dyson",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m024",
        "description": "Dyson V15 Detect cordless vacuum cleaner in like new condition."
    }
]
